apps/novedades/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'novedades'


urlpatterns = [

	path('ALTA_N/', views.Alta_Novedad, name = 'cargar_n'),
	path('ALTA_C/', views.Alta_Categoria.as_view() , name = 'cargar_c'),
	path('Listar/', views.Listar , name = 'listar'),
	path('post/<int:pk>/', views.post_detalle, name='post_detalle'),
	path('post/<int:pk>/edit/', views.Alta_edit, name='Alta_edit'),
	re_path(r'^post/(?P<pk>\d+)/comentar/$', views.agregar_comentario, name='agregar_comentario'),
	path('filtrar/', views.filtrar, name = 'filtrar'),
	path('filtro/', views.NovedadListView.as_view(), name='filtro'),


 
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/urls.py
from django.urls import path
from . import views


app_name = 'usuarios'


urlpatterns = [

	
	path('Registro/', views.Registrar_usuario.as_view() , name ="registrar_usuario"),
	path('Listar_u/', views.Listar_usuario , name = 'listar_usuarios')
 
    
]

webNoticias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views



from django.contrib.auth import views as auth


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Principal, name = 'home'),
    path('Pantalla2/', views.Segunda, name = 'segunda_pantalla'),

    path('Novedades/', include('apps.novedades.urls')),

    
    path('Usuarios/', include('apps.usuarios.urls')),
    path('Login/',auth.LoginView.as_view(template_name="usuarios/login.html"),name="login"),
    path('Logout/',auth.LogoutView.as_view(),name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/novedades/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Categoria(models.Model):
	nombre = models.CharField(max_length = 50)

	def __str__(self):
		return self.nombre

class Novedad(models.Model):
	titulo = models.CharField(max_length = 200)
	categoria = models.ForeignKey('Categoria', on_delete = models.CASCADE)
	texto = models.TextField()
	imagen = models.ImageField(upload_to = 'novedades')
	author = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE)
	published_date = models.DateTimeField()

	
	def __str__(self):
		return self.titulo

class Comentario(models.Model):
    post = models.ForeignKey('novedades.Novedad', on_delete=models.CASCADE, related_name='comentarios')
    author = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE)
    texto = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.text

class Filtro_categoria(models.Model):
	categoria = models.ForeignKey('Categoria', on_delete = models.CASCADE)

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
	nacionalidad = models.CharField(max_length = 30, null = True)

apps/novedades/forms.py
from django import forms
from .models import *
from django.forms.widgets import SelectDateWidget


class Formulario_Alta_Novedad(forms.ModelForm):

	class Meta:
		model = Novedad
		fields =  ['titulo','categoria','texto','imagen']

class Formulario_Alta_Categoria(forms.ModelForm):

	class Meta:
		model = Categoria
		fields = '__all__'


class Formulario_filtro(forms.ModelForm):

	class Meta:
		model = Novedad
		fields = ['categoria']

class ComentarioForm(forms.ModelForm):

    class Meta:
        model = Comentario
        fields = ['texto']

apps/usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class RegistroUsuarioForm(UserCreationForm):

	class Meta:
		model = Usuario
		fields = ['username','email','first_name','last_name','password1','password2']

		
	

apps/novedades/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django import template
from  django.http import HttpResponse
from .filters import PostFilter

# Create your views here.




def Listar(request):
    novedad= Novedad.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'novedades/listar.html', {'novedad':novedad})

def post_detalle(request, pk):
    novedad = get_object_or_404(Novedad, pk=pk)
    return render(request, 'novedades/post_detalle.html', {'novedad': novedad})

def filtrar(request):
    return render(request, 'novedades/f_categoria.html')

@login_required
def Alta_Novedad(request):
    if request.method == "POST":
        form = Formulario_Alta_Novedad(request.POST, request.FILES)
        if form.is_valid():
            novedad = form.save(commit=False)
            novedad.author = request.user
            novedad.published_date = timezone.now()
            novedad.save()
            return redirect('novedades:post_detalle', pk=novedad.pk)
    else:
        form = Formulario_Alta_Novedad()
    return render(request,'novedades/alta_novedad.html', {'form': form})

def Alta_edit(request, pk):
    novedad = get_object_or_404(Novedad, pk=pk)
    if request.method == "POST":
        form = Formulario_Alta_Novedad(request.POST, request.FILES, instance=novedad)
        if form.is_valid():
            novedad = form.save(commit=False)
            novedad.author = request.user
            novedad.published_date = timezone.now()
            novedad.save()
            return redirect('novedades:post_detalle', pk=novedad.pk)
    else:
        form = Formulario_Alta_Novedad(instance=novedad)
    return render(request, 'novedades/alta_novedad.html', {'form': form})

class Alta_Categoria(LoginRequiredMixin, CreateView):
	model = 'Categoria'
	form_class = Formulario_Alta_Categoria
	template_name = 'novedades/alta_categoria.html'
	success_url = reverse_lazy('home')

@login_required
def agregar_comentario(request, pk):
    novedad = get_object_or_404(Novedad, pk=pk)
    if request.method == "POST":
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.novedad = novedad
            comentario.author = request.user
            comentario.post_id = novedad.pk
            comentario.save()
            return redirect('novedades:post_detalle', pk=novedad.pk)
    else:
        form = ComentarioForm()
    return render(request, 'novedades/agregar_comentario.html', {'form': form})


class NovedadListView(ListView):
    model = Novedad
    template_name = 'novedades/filtro.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset().order_by('-published_date'))
        return context

apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RegistroUsuarioForm
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario


from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def Listar_usuario(request):

	usuarios = Usuario.objects.all()
	ctx = {}
	ctx['p'] = usuarios
	return render(request, 'usuarios/listar_usuarios.html',ctx)


class Registrar_usuario(CreateView):
	model = 'Usuario'
	form_class = RegistroUsuarioForm
	template_name = 'usuarios/signup.html'
	success_url = reverse_lazy('home')

webNoticias/views.py
from django.shortcuts import render

def Principal(request):

	return render(request,'home.html')

def Segunda(request):

	return render(request,'segunda.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Blog de Noticias</title>
 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
 <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
 <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	    <ul class="nav navbar-nav">
	      <li class="active">
	        <a class="navbar-brand" href="{% url 'home' %}">Home
	        </a>
	      </li>
	      <li class="active">
	        <a class="navbar-brand" href="{% url 'novedades:listar' %}">Ver posts</a>
	      </li>
	      <li class="active">
	        <a class="navbar-brand"href="{% url 'novedades:cargar_n'%}">Crear post</a>
	      </li>
	      <li class="active">
	        <a class="navbar-brand"href="{% url 'novedades:filtro' %}">Filtrar posts</a>
	      </li>
	      {% if user.is_staff %}
	      <li class="active">
	        <a class="navbar-brand"" href="{% url 'novedades:cargar_c'%}">Cargar nueva categoria</a>
	      </li>
	      <li class="active">
	        <a class="navbar-brand" href="{% url 'usuarios:listar_usuarios'%}">Listar Usuarios</a>
	      </li>
	      {% endif %}
	    </ul>
	    <form>
	      {% if user.is_authenticated %}
	       <button type="submit"  class="btn btn-primary " style="float: right">
	      	{{user.username}}
	      </button>
	      <a href="{% url 'logout' %}" class="btn btn-secondary active" role="button" aria-pressed="true" style="float: right">SALIR</a>
	      {% else %}
	      	<a href="{% url 'login' %}" class="btn btn-secondary active" role="button" aria-pressed="true" style="float: right">ACCEDER</a>
	      	<a href="{% url 'usuarios:registrar_usuario' %}" class="btn btn-secondary active" role="button" aria-pressed="true" style="float: right">REGISTRARSE</a>
	      {% endif %}
	    </form>
	</nav>
	<div class="page-header">
    	<h1><a href="/">Blog de Noticias</a></h1>
	</div>		
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
			
	{% block content %}

	{% endblock content %}
                </div>
            </div>
        </div>

	<footer><h2>BLOG DE NOTICIAS</h2></footer>
</body>
</html>

templates/home.html
{% extends 'base.html'  %}
{% load static %}

	{% block content %}
	<div class="post">
		<h1>INFORMATORIO 2021 DJANGO</h1>
		<img class="img-responsive" src="{% static 'portada_home/django2.jpg' %}">
	</div>
	{% endblock content %}	

templates/novedades/agregar_comentario.html
{% extends 'base.html' %}

{% block content %}
    <h1>Nuevo comentario</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Comentar</button>
    </form>
{% endblock %}

templates/novedades/alta_categoria.html
{% extends 'base.html'  %}

{% block content %}
   {% if user.is_staff %}
	<h1>CARGAR UNA NUEVA CATEGORIA</h1>
	<div style="margin: 50px;">
		<form method="POST" enctype="multipart/form-data">{% csrf_token %}
			{{form.as_p}}


			<input type="submit" name="Guardar" value="Guardar">



		</form>

	</div>
	{% endif %}


{% endblock content %}

templates/novedades/alta_novedad.html
{% extends 'base.html' %}

{% block content %}

	<div>
		<form method="post" class="post-form" enctype="multipart/form-data" >
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit"  class="save btn btn-default" name="Crear" value="Publicar">
		</form>
	

	</div>
{% endblock content %}

templates/novedades/filtro.html
{% extends 'base.html'  %}

{% load bootstrap %}

	{% block content %}
<div class="content container">
	<h2>Filtrar Posts por:</h2>

	
		<form>
			{{ filter.form|bootstrap }}
			<button type="submit" class="btn btn-primary">Buscar</button>
		</form>
		<hr>
</div>
<div class="post">
	<ul>
		{% for novedad in filter.qs %}
		<li>
			{{novedad.author}}
			<p>{{novedad.published_date}}</p>
			<h1><a href="{% url 'novedades:post_detalle' novedad.id %} ">{{ novedad.titulo }}</a></h1>
			<h5>{{novedad.categoria}}</h5>
			<img src="{{novedad.imagen.url}}" alt="{{image.name}}" style="width:500px;">
			<p>{{novedad.texto|linebreaksbr}}</p>
			<a href="{% url 'novedades:post_detalle' pk=novedad.pk %}">Comentarios: {{ novedad.comentarios.count }}</a>
			<hr>
		</li>
		{% endfor %}
	</ul>
</div>
	{% endblock content %}			

templates/novedades/listar.html
{% extends 'base.html'  %}

	{% block content %}

		<h3>LISTA DE NOVEDADES</h3>

		<h3>Filtro</h3>

		{% for novedad in novedad_list %}
			<p>{{novedad.nombre}}</p>
			<p>{{novedad.categoria}}</p>
			<p><img src="{{novedad.imagen.url}}" alt="{{image.name}}" style="width:150px;"></p>
			<p>{{novedad.texto}}</p>
			<p>-------------------</p>
		{% endfor %}



	{% endblock content %}	

templates/novedades/post_detalle.html
{% extends 'base.html'  %}

	{% block content %}


	<div>
		{% if request.user == novedad.author %}
		<a class="btn btn-default" href="{% url 'novedades:Alta_edit' pk=novedad.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
		{% endif %}
			{{novedad.author}}
		<div class="date">
			<p>{{novedad.published_date}}</p>
		</div>
			<h1><a href="">{{novedad.titulo}}</a></h1>
			<h5>{{novedad.categoria}}</h5>
			<img src="{{novedad.imagen.url}}" alt="{{image.name}}" style="width:500px;">
			<br>
			<br>
			<p>{{novedad.texto|linebreaksbr}}</p>
		<br>
	</div>
		<hr>
{% for comentario in novedad.comentarios.all %}
    <div class="comment">
        <div class="date">{{ comentario.created_date }}</div>
        <strong>{{ comentario.author }}</strong>
        <p>{{ comentario.texto|linebreaks }}</p>
    </div>
{% empty %}
    <p>Aún no hay comentarios</p>
{% endfor %}
	<a class="btn btn-default" href="{% url 'novedades:agregar_comentario' pk=novedad.pk %}">Comentar</a>




	{% endblock content %}	

templates/usuarios/listar_usuarios.html
{% extends 'base.html'  %}

	{% block content %}
{% if user.is_staff %}
		<h3>LISTA DE USUARIOS</h3>

		{% for usuario in p %}
			<p><h2>{{usuario.username}}</h2></p>
			<p>{{usuario.email}}</p>
			<p>{{usuario.first_name}}</p>
			<p>{{usuario.last_name}}</p>
			<p>-------------------</p>
		{% endfor %}

{% endif %}

	{% endblock content %}	

templates/usuarios/login.html
{% extends 'base.html'  %}

{% block content %}
{% load crispy_forms_tags %}
<div class="form-group">
		<form method="POST">{%csrf_token%}
			{{form|crispy}}


			<input type="submit" name="" value="INICIAR SESION" class="btn btn-success">
		</form>
</div>
{% endblock content %}

templates/usuarios/signup.html
{% extends 'base.html'  %}

{% block content %}

  <div style="margin: 50px;">
  	{% load crispy_forms_tags %}
    <form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}

    	 {{ form|crispy }}
      <input type="submit" value="Registrarse" class="btn btn-success">


       

    </form>

  </div>

{% endblock content %}